[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd aplicativo && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"

[build.vars]
NIXPACKS_NODE_VERSION = "18"